# Source: atm/charts/ms-fake-uno/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atm-ms-fake-uno
  labels:
    helm.sh/chart: ms-fake-uno-0.3.0
    app.kubernetes.io/name: ms-fake-uno
    app.kubernetes.io/instance: atm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
