# Source: atm/charts/ms-fake-dos/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm-ms-fake-dos
  labels:
    helm.sh/chart: ms-fake-dos-0.3.0
    app.kubernetes.io/name: ms-fake-dos
    app.kubernetes.io/instance: atm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ms-fake-dos
      app.kubernetes.io/instance: atm
  template:
    metadata:
      annotations:
        checksum/config-env: 35e78e36036750db5c0c8414004e9f2f874efd875b438820afe8760d295bccff
        checksum/config-file: 73bc7d5592daf911725fb4e21e4e57e84cd784d894c5ce3bb468e555cd4fce72
      labels:
        app.kubernetes.io/name: ms-fake-dos
        app.kubernetes.io/instance: atm
    spec:
      serviceAccountName: atm-ms-fake-dos
      containers:
        - name: ms-fake-dos
          image: "nginx:1.30.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: atm-ms-fake-dos-env
            - secretRef:
                name: atm-ms-fake-dos
          volumeMounts:
            - name: config
              mountPath: /etc/app
              readOnly: true
          resources:
            {}
      volumes:
        - name: config
          configMap:
            name: atm-ms-fake-dos-file
