# Source: atm/charts/ms-fake-dos/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atm-ms-fake-dos
  labels:
    helm.sh/chart: ms-fake-dos-0.3.0
    app.kubernetes.io/name: ms-fake-dos
    app.kubernetes.io/instance: atm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: atm-ms-fake-dos
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - remoteRef:
        key: /practica/atm/ms-fake-dos/db/password
      secretKey: DB_PASSWORD
