# Source: atm/charts/ms-fake-tres/templates/configmap-env.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: atm-ms-fake-tres-env
  labels:
    helm.sh/chart: ms-fake-tres-0.3.0
    app.kubernetes.io/name: ms-fake-tres
    app.kubernetes.io/instance: atm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  APP_MODE: "PRO_TRES"
  LOG_LEVEL: "info"
  RDS_HOST: "postgres-bd-tres.demo.local"
