# Source: atm/charts/ms-fake-dos/templates/configmap-file.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: atm-ms-fake-dos-file
  labels:
    helm.sh/chart: ms-fake-dos-0.3.0
    app.kubernetes.io/name: ms-fake-dos
    app.kubernetes.io/instance: atm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
data:
  application.yml: |
    server:
      port: 8080
    datasource:
      url: jdbc:postgresql://${RDS_HOST}:5434/atm_dos
      username: atm_dos
      password: ${DB_PASSWORD}
