# Source: atm/charts/ms-fake-tres/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: atm-ms-fake-tres
  labels:
    helm.sh/chart: ms-fake-tres-0.3.0
    app.kubernetes.io/name: ms-fake-tres
    app.kubernetes.io/instance: atm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ms-fake-tres
    app.kubernetes.io/instance: atm
