# Source: atm/charts/ms-fake-tres/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atm-ms-fake-tres
  labels:
    helm.sh/chart: ms-fake-tres-0.3.0
    app.kubernetes.io/name: ms-fake-tres
    app.kubernetes.io/instance: atm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: atm-ms-fake-tres
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - remoteRef:
        key: /practica/atm/ms-fake-tres/db/password
      secretKey: DB_PASSWORD
