apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: /practica/atm/ms-fake-uno/db/password
          value: "s3cret-uno"
        - key: /practica/atm/ms-fake-dos/db/password
          value: "s3cret-dos"
        - key: /practica/atm/ms-fake-tres/db/password
          value: "s3cret-tres"